version: '3.4'

services:
  typescriptstarter:
    image: typescriptstarter
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
