services:
  app:
    build:
      context: ../../app                     # Ajusta al path correcto
      dockerfile: ../docker/debug/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../../app:/usr/src/app